src/Entity/BoardSettings.php
<?php

namespace App\Entity;

use App\Repository\BoardSettingsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoardSettingsRepository::class)]
class BoardSettings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'boardSettings', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Board $board = null;

    #[ORM\Column]
    private ?bool $display_status_title = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoard(): ?Board
    {
        return $this->board;
    }

    public function setBoard(Board $board): self
    {
        $this->board = $board;

        return $this;
    }

    public function isDisplayStatusTitle(): ?bool
    {
        return $this->display_status_title;
    }

    public function setDisplayStatusTitle(bool $display_status_title): self
    {
        $this->display_status_title = $display_status_title;

        return $this;
    }
}

src/Form/BoardSettingsType.php
<?php

namespace App\Form;

use App\Entity\BoardSettings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BoardSettingsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('display_status_title')
            ->add('board')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BoardSettings::class,
        ]);
    }
}

src/Controller/BoardSettingsController.php
<?php

namespace App\Controller;

use App\Entity\BoardSettings;
use App\Form\BoardSettingsType;
use App\Repository\BoardSettingsRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[IsGranted("ROLE_ADMIN")]
#[Route('/board/settings')]
class BoardSettingsController extends AbstractController
{
    #[Route('/', name: 'app_board_settings_index', methods: ['GET'])]
    public function index(BoardSettingsRepository $boardSettingsRepository): Response
    {
        return $this->render('board_settings/index.html.twig', [
            'board_settings' => $boardSettingsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_board_settings_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BoardSettingsRepository $boardSettingsRepository): Response
    {
        $boardSetting = new BoardSettings();
        $form = $this->createForm(BoardSettingsType::class, $boardSetting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $boardSettingsRepository->add($boardSetting, true);

            return $this->redirectToRoute('app_board_settings_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('board_settings/new.html.twig', [
            'board_setting' => $boardSetting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_board_settings_show', methods: ['GET'])]
    public function show(BoardSettings $boardSetting): Response
    {
        return $this->render('board_settings/show.html.twig', [
            'board_setting' => $boardSetting,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_board_settings_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BoardSettings $boardSetting, BoardSettingsRepository $boardSettingsRepository): Response
    {
        $form = $this->createForm(BoardSettingsType::class, $boardSetting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $boardSettingsRepository->add($boardSetting, true);

            return $this->redirectToRoute('app_board_settings_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('board_settings/edit.html.twig', [
            'board_setting' => $boardSetting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_board_settings_delete', methods: ['POST'])]
    public function delete(Request $request, BoardSettings $boardSetting, BoardSettingsRepository $boardSettingsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$boardSetting->getId(), $request->request->get('_token'))) {
            $boardSettingsRepository->remove($boardSetting, true);
        }

        return $this->redirectToRoute('app_board_settings_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/board_settings/_delete_form.html.twig
<form method="post" action="{{ path('app_board_settings_delete', {'id': board_setting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ board_setting.id) }}">
    <button class="btn">Delete</button>
</form>

templates/board_settings/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/board_settings/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BoardSettings{% endblock %}

{% block body %}
    <h1>Edit BoardSettings</h1>

    {{ include('board_settings/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_board_settings_index') }}">back to list</a>

    {{ include('board_settings/_delete_form.html.twig') }}
{% endblock %}

templates/board_settings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BoardSettings index{% endblock %}

{% block body %}
    <h1>BoardSettings index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Display_status_title</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for board_setting in board_settings %}
            <tr>
                <td>{{ board_setting.id }}</td>
                <td>{{ board_setting.displayStatusTitle ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_board_settings_show', {'id': board_setting.id}) }}">show</a>
                    <a href="{{ path('app_board_settings_edit', {'id': board_setting.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_board_settings_new') }}">Create new</a>
{% endblock %}

templates/board_settings/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BoardSettings{% endblock %}

{% block body %}
    <h1>Create new BoardSettings</h1>

    {{ include('board_settings/_form.html.twig') }}

    <a href="{{ path('app_board_settings_index') }}">back to list</a>
{% endblock %}

templates/board_settings/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BoardSettings{% endblock %}

{% block body %}
    <h1>BoardSettings</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ board_setting.id }}</td>
            </tr>
            <tr>
                <th>Display_status_title</th>
                <td>{{ board_setting.displayStatusTitle ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_board_settings_index') }}">back to list</a>

    <a href="{{ path('app_board_settings_edit', {'id': board_setting.id}) }}">edit</a>

    {{ include('board_settings/_delete_form.html.twig') }}
{% endblock %}